data:
  paths:
    train_local: data/panaf500_ar/train.csv
    val_local: data/panaf500_ar/val.csv
    test_local: data/panaf500_ar/test.csv
  data_path: data/panaf500_ar/videos
  num_views_per_segment_val: 3
  embed_dim_global: null
  embed_dim_local: 1024
  num_workers: 12
  mode: video
  memory_caching: True
  use_caching: True
  dataset_type: panaf500
optimization:
  batch_size: 8
  val_batch_size: 128
  num_epochs: 40
  weight_decay: 0.01
  lr: 1.e-3
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: false
  loss_fn: cross_entropy
  n_classifiers: 5
  buffer_size: 200
head_type: privi
head:
  depth: 3
  embed_dim: 64
  norm_input: true
backbone_type: vjepa
backbone:
  pretrained_path: data/privi_original.pth
  model_name: vit_large
  patch_size: 16
  tubelet_size: 2
  uniform_power: true
  checkpoint_key: target_encoder
  use_silu: false
  tight_silu: false
  use_sdpa: true
  dtype: float16
  out_layers: [23]
  training_mode: frozen
data_aug:
  random_resize_aspect_ratio: [0.75, 1.333333]
  random_resize_scale: [0.3, 1.0]
  reprob: 0.0
  auto_augment: False
  motion_shift: False
  random_horizontal_flip: True
meta:
  save_dir: data/
  n_trials: 1
  val_every_n_samples: 10000
  
# Uncomment for evaluation on test set
#ckpts: data/checkpoints/frozen_head/RUN_NAME
#head_epochs: [BEST_VAL_EPOCHS] # e.g. [16.68, 16.68, 17.78, 8.98, 18.88]